<?php

namespace AppBundle\Repository;

/**
 * CaracteristicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristicaRepository extends \Doctrine\ORM\EntityRepository
{
}
