<?php

namespace AppBundle\Repository;

/**
 * Caracteristica_modelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Caracteristica_modelRepository extends \Doctrine\ORM\EntityRepository
{
}
