<?php

namespace AppBundle\Repository;

/**
 * CriterioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriterioRepository extends \Doctrine\ORM\EntityRepository
{
}
