<?php

namespace AppBundle\Repository;

/**
 * EncuestaProfesoresAutoevaluacionDoctoradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuestaProfesoresAutoevaluacionDoctoradoRepository extends \Doctrine\ORM\EntityRepository
{
}
