<?php

namespace AppBundle\Repository;

/**
 * EncuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuestaRepository extends \Doctrine\ORM\EntityRepository
{
}
