<?php

namespace AppBundle\Repository;

/**
 * EncuestaDoctoradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuestaDoctoradoRepository extends \Doctrine\ORM\EntityRepository
{
}
