<?php

namespace AppBundle\Repository;

/**
 * EncuestaMaestriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuestaMaestriaRepository extends \Doctrine\ORM\EntityRepository
{
}
