<?php

namespace AppBundle\Repository;

/**
 * EstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudianteRepository extends \Doctrine\ORM\EntityRepository
{
}
