<?php

namespace AppBundle\Repository;

/**
 * FactorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactorRepository extends \Doctrine\ORM\EntityRepository
{
}
