<?php

namespace AppBundle\Repository;

/**
 * Indicador_modelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Indicador_modelRepository extends \Doctrine\ORM\EntityRepository
{
}
