<?php

namespace AppBundle\Repository;

/**
 * IndicadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicadorRepository extends \Doctrine\ORM\EntityRepository
{
}
