<?php

namespace AppBundle\Repository;

/**
 * ModeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeloRepository extends \Doctrine\ORM\EntityRepository
{
}
