<?php

namespace AppBundle\Repository;

/**
 * PerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilRepository extends \Doctrine\ORM\EntityRepository
{
}
