<?php

namespace AppBundle\Repository;

/**
 * PrincipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrincipioRepository extends \Doctrine\ORM\EntityRepository
{
}
